version: 2
updates:
  # Main project
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"

  # telegram-torrent-bot
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "slick-autobuild"
    commit-message:
      prefix: "deps(slick-autobuild)"
      include: "scope"

  # Docker support for telegram-torrent-bot
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "docker"
      - "dependencies"
      - "slick-autobuild"
    commit-message:
      prefix: "docker(slick-autobuild)"
      include: "scope"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "ci-cd"
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"
