name: Telegram notify via Bitwarden SM

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Fetch secrets from Bitwarden SM
      - name: Get Secrets
        id: secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          # For Bitwarden Cloud, omit base_url; optionally set cloud_region: us|eu
          cloud_region: us
          secrets: |
            2f3b9e39-4af4-463e-bfae-b35400c41034 > TELEGRAM_CHAT_ID
            7ceeeaf0-9ce5-4fde-ad1a-b35400c3dcd4 > TELEGRAM_BOT_TOKEN

      # 2) Extra masking & sanity checks (no secret printed)
      - name: Mask and validate
        shell: bash
        run: |
          set -euo pipefail

          # Belt & suspenders masking
          [ -n "${TELEGRAM_CHAT_ID:-}" ] && echo "::add-mask::$TELEGRAM_CHAT_ID"
          [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && echo "::add-mask::$TELEGRAM_BOT_TOKEN"

          # Non-empty checks
          if [ -z "${TELEGRAM_CHAT_ID:-}" ]; then
            echo "TELEGRAM_CHAT_ID is empty"; exit 1
          fi
          if [ -z "${TELEGRAM_BOT_TOKEN:-}" ]; then
            echo "TELEGRAM_BOT_TOKEN is empty"; exit 1
          fi

          # Optional: basic format checks (adjust to your case)
          # Chat IDs are usually integers; channels/groups may be negative.
          if ! [[ "$TELEGRAM_CHAT_ID" =~ ^-?[0-9]+(,-?[0-9]+)*$ ]]; then
            echo "Warning: TELEGRAM_CHAT_ID doesn't look numeric; continuing anyway."
          fi
          if ! [[ "$TELEGRAM_BOT_TOKEN" =~ ^[0-9]+:[A-Za-z0-9_-]+$ ]]; then
            echo "Warning: TELEGRAM_BOT_TOKEN doesn't match expected token format; continuing anyway."
          fi

          # Debug without leaking: show lengths only
          echo "TELEGRAM_CHAT_ID length: ${#TELEGRAM_CHAT_ID}"
          echo "TELEGRAM_BOT_TOKEN length: ${#TELEGRAM_BOT_TOKEN}"

      # 3) Send Telegram message (use GHA expressions, not $VAR)
      - name: Send Telegram notification
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: ${{ env.TELEGRAM_CHAT_ID }}
          token: ${{ env.TELEGRAM_BOT_TOKEN }}
          message: |
            🧪 Go Unit Tests: ✅ Success

